---
- name: Install Smokeping Prerequisites
  become: yes
  hosts: all
  tasks:
    - name: Install Prerequisites
      apt: name={{ item }} update_cache=yes
      with_items:
       - rrdtool
       - perl
       - fcgiwrap
       - build-essential
       - librrds-perl
       - fping
       - nginx

    - name: Get cpanm
      get_url:
        url: https://raw.github.com/miyagawa/cpanminus/master/cpanm
        dest: /opt/cpanm
        mode: a+x
      register: getcpan

    - name: Symlink cpanm
      file:
        src: /opt/cpanm
        dest: /usr/local/bin/cpanm
        state: link
      when: getcpan.changed

    - name: Upgrade cpanm
      shell: cpanm --self-upgrade --sudo
      when: getcpan.changed

    - name: Install perl modules
      cpanm: name={{ item }}
      with_items:
        - FCGI
        - CGI
        - CGI::Fast
        - Config::Grammar
        - LWP
        - Net::DNS
        - Net::Telnet
        - Net::OpenSSH
        - Net::SNMP
        - Net::LDAP
        - IO::Pty

- name: Install smokeping
  become: yes
  hosts: all
  vars:
    smokeping_version: 2.6.11
    smokeping_cli_version: "2.006011" # For some reason smokeping --version displays a version formatted like this
    smokeping_base_url: "http://localhost/"
    image_cache_dir: /opt/smokeping/cache
    data_dir: /opt/smokeping/data
    pid_dir: /opt/smokeping/var
    install_smokeping: False
  tasks:
    - name: Get smokeping version
      command: /opt/smokeping/bin/smokeping --version
      changed_when: false
      failed_when: false
      register: smokeping_installed_version

    - name: Determine whether to install Smokeping
      set_fact:
        install_smokeping: True
      when: smokeping_installed_version.rc == 2 or smokeping_installed_version.stdout != smokeping_cli_version

    - name: Download smokeping
      get_url:
        url: http://oss.oetiker.ch/smokeping/pub/smokeping-{{ smokeping_version }}.tar.gz
        dest: /tmp/smokeping.tar.gz
      when: install_smokeping

    - name: Create unpack dir
      file: path=/tmp/smokeping state=directory
      when: install_smokeping

    - name: Unpack smokeping.tar.gz
      unarchive:
        src: /tmp/smokeping.tar.gz
        dest: /tmp/smokeping/
        creates: /tmp/smokeping/README
      when: install_smokeping

    - name: Install smokeping from source
      command: "{{ item }}"
      args:
        chdir: /tmp/smokeping/smokeping-{{ smokeping_version }}
      items:
        - ./configure --prefix=/opt/smokeping
        - make install
      when: install_smokeping

    - name: init.d script
      template:
        src: templates/smokeping-initd.sh.j2
        dest: /etc/init.d/smokeping
        mode: a+x

    - name: update-rc.d for smokeping
      command: update-rc.d smokeping defaults

    - name: Smokeping config
      template:
        src: templates/smokeping-config.j2
        dest: /opt/smokeping/etc/config

    - name: Create Smokeping working directories
      file: path={{ item }} state=directory
      with_items:
        - "{{ data_dir }}"
        - "{{ pid_dir }}"

    - name: Create Smokeping cache directory
      file: path="{{ image_cache_dir }}" state=directory owner=www-data

    - name: Enable Smokeping service
      service: name=smokeping state=started enabled=yes

    - name: Enable smokeping fcgi script
      file:
        src: /opt/smokeping/htdocs/smokeping.fcgi.dist
        dest: /opt/smokeping/htdocs/smokeping.fcgi
        state: link

    - name: Nginx.conf
      template:
        src: templates/nginx-conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Add Smokeping nginx configuration
      template:
        src: templates/nginx-smokeping.j2
        dest: /etc/nginx/sites-available/smokeping.conf

    - name: Activate Smokeping nginx site
      file:
        src: /etc/nginx/sites-available/smokeping.conf
        dest: /etc/nginx/sites-enabled/smokeping.conf
        state: link

    - name: Restart nginx
      service: name=nginx state=restarted
